const GET_COUNTRIES="GET_COUNTRIES";
const GET_COUNTRY="GET_COUNTRY";
const CLEAN="CLEAN";
const CURRENT_PAGE="CURRENT_PAGE";


export{
    GET_COUNTRIES,
    GET_COUNTRY,
    CLEAN,
    CURRENT_PAGE
}