const GET_COUNTRIES="GET_COUNTRIES";
const GET_COUNTRY="GET_COUNTRY";
const CLEAN="CLEAN";
const CURRENT_PAGE="CURRENT_PAGE";
const ACTIVITIES_ACTU="ACTIVITIES_ACTU";

export{
    GET_COUNTRIES,
    GET_COUNTRY,
    CLEAN,
    CURRENT_PAGE,
    ACTIVITIES_ACTU
}